[target.armv7-unknown-linux-gnueabihf]
xargo = false
dockerfile = "./crabidy-server/armv7-unknown-linux-gnueabihf-Dockerfile"

[target.aarch64-unknown-linux-gnu]
xargo = false
dockerfile = "./crabidy-server/aarch64-unknown-linux-gnu-Dockerfile"

