name: CI checks
run-name: CI checks that run when main branch is changed
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: ubuntu / stable / fmt
    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check --all
